HAI 1.2
  OBTW
        I HAZ MY FIRST LOLCODE HAI
  TLDR
  CAN HAS STDIO?
  VISIBLE "HAI WORLD!!!1!"

  I HAS A KITTYCOUNT ITZ 1

  IM IN YR KILLKITTIES UPPIN YR KITTYCOUNT TIL BOTH SAEM KITTYCOUNT AN 10
    VISIBLE "IVE KILLED " KITTYCOUNT " KITTIES!"
  IM OUTTA YR KILLKITTIES
KTHXBYE

